########################################################################################################################################################################################################################################################################################################################################################################################################
# F7 CURTAIN

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_HUIYISHI_1_ADJUST','BIAD_KNX_DEVICES&0x619','0x619',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_HUIYISHI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_HUIYISHI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x47','0x47',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_HUIYISHI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XIUXIANSHI_2_ADJUST','BIAD_KNX_DEVICES&0x618','0x618',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XIUXIANSHI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XIUXIANSHI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x45','0x45',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XIUXIANSHI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XIUXIANSHI_1_ADJUST','BIAD_KNX_DEVICES&0x617','0x617',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XIUXIANSHI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XIUXIANSHI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x43','0x43',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XIUXIANSHI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_HUIYISHI_2_ADJUST','BIAD_KNX_DEVICES&0x616','0x616',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_HUIYISHI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_HUIYISHI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x12','0x12',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_HUIYISHI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_SUOZHANGSHI_2_ADJUST','BIAD_KNX_DEVICES&0x615','0x615',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_SUOZHANGSHI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_SUOZHANGSHI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x14','0x14',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_SUOZHANGSHI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_12_ADJUST','BIAD_KNX_DEVICES&0x614','0x614',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_12_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_12_OPENCLOSE','BIAD_KNX_DEVICES&0x3D','0x3D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_12_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_11_ADJUST','BIAD_KNX_DEVICES&0x613','0x613',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_11_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_11_OPENCLOSE','BIAD_KNX_DEVICES&0x3B','0x3B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_11_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_10_ADJUST','BIAD_KNX_DEVICES&0x612','0x612',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_10_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_10_OPENCLOSE','BIAD_KNX_DEVICES&0x39','0x39',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_10_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_9_ADJUST','BIAD_KNX_DEVICES&0x611','0x611',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_9_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_9_OPENCLOSE','BIAD_KNX_DEVICES&0x37','0x37',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_9_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_8_ADJUST','BIAD_KNX_DEVICES&0x610','0x610',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_8_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_8_OPENCLOSE','BIAD_KNX_DEVICES&0x35','0x35',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_8_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_7_ADJUST','BIAD_KNX_DEVICES&0x60E','0x60E',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_7_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_7_OPENCLOSE','BIAD_KNX_DEVICES&0x31','0x31',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_7_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_6_ADJUST','BIAD_KNX_DEVICES&0x60F','0x60F',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_6_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_6_OPENCLOSE','BIAD_KNX_DEVICES&0x33','0x33',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_6_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_5_ADJUST','BIAD_KNX_DEVICES&0x60D','0x60D',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_5_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_5_OPENCLOSE','BIAD_KNX_DEVICES&0x2F','0x2F',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_5_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_4_ADJUST','BIAD_KNX_DEVICES&0x60C','0x60C',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_4_OPENCLOSE','BIAD_KNX_DEVICES&0x2D','0x2D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_3_ADJUST','BIAD_KNX_DEVICES&0x60B','0x60B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_3_OPENCLOSE','BIAD_KNX_DEVICES&0x2B','0x2B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_2_ADJUST','BIAD_KNX_DEVICES&0x60A','0x60A',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x29','0x29',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_1_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_XI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_XI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_BANGONGSHI_ADJUST','BIAD_KNX_DEVICES&0x608','0x608',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_BANGONGSHI_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_BANGONGSHI_OPENCLOSE','BIAD_KNX_DEVICES&0x36','0x36',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_BANGONGSHI_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_4_ADJUST','BIAD_KNX_DEVICES&0x607','0x607',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_4_OPENCLOSE','BIAD_KNX_DEVICES&0x35','0x35',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_3_ADJUST','BIAD_KNX_DEVICES&0x606','0x606',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_3_OPENCLOSE','BIAD_KNX_DEVICES&0x34','0x34',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_2_ADJUST','BIAD_KNX_DEVICES&0x605','0x605',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x33','0x33',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_1_ADJUST','BIAD_KNX_DEVICES&0x604','0x604',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_YUANZHANGSHI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x32','0x32',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_YUANZHANGSHI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_KUAIJISHI_ADJUST','BIAD_KNX_DEVICES&0x603','0x603',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_KUAIJISHI_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_KUAIJISHI_OPENCLOSE','BIAD_KNX_DEVICES&0x31','0x31',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_KUAIJISHI_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_1_ADJUST','BIAD_KNX_DEVICES&0x602','0x602',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_1_OPENCLOSE','BIAD_KNX_DEVICES&0x19','0x19',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_2_ADJUST','BIAD_KNX_DEVICES&0x623','0x623',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_2_OPENCLOSE','BIAD_KNX_DEVICES&0x5B','0x5B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_3_ADJUST','BIAD_KNX_DEVICES&0x622','0x622',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_3_OPENCLOSE','BIAD_KNX_DEVICES&0x59','0x59',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_4_ADJUST','BIAD_KNX_DEVICES&0x601','0x601',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_4_OPENCLOSE','BIAD_KNX_DEVICES&0x17','0x17',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_5_ADJUST','BIAD_KNX_DEVICES&0x600','0x600',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_5_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_5_OPENCLOSE','BIAD_KNX_DEVICES&0x15','0x15',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_5_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_6_ADJUST','BIAD_KNX_DEVICES&0x621','0x621',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_6_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_6_OPENCLOSE','BIAD_KNX_DEVICES&0x57','0x57',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_6_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_7_ADJUST','BIAD_KNX_DEVICES&0x620','0x620',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_7_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_7_OPENCLOSE','BIAD_KNX_DEVICES&0x55','0x55',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_7_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_8_ADJUST','BIAD_KNX_DEVICES&0x61E','0x61E',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_8_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_8_OPENCLOSE','BIAD_KNX_DEVICES&0x51','0x51',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_8_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_9_ADJUST','BIAD_KNX_DEVICES&0x61F','0x61F',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_9_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_9_OPENCLOSE','BIAD_KNX_DEVICES&0x53','0x53',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_9_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_10_ADJUST','BIAD_KNX_DEVICES&0x61D','0x61D',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_10_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_10_OPENCLOSE','BIAD_KNX_DEVICES&0x4F','0x4F',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_10_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_11_ADJUST','BIAD_KNX_DEVICES&0x61C','0x61C',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_11_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_11_OPENCLOSE','BIAD_KNX_DEVICES&0x4D','0x4D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_11_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_12_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_12_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_DONG_12_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_DONG_12_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_SUOZHANGSHI_1_ADJUST','BIAD_KNX_DEVICES&0x61A','0x61A',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_SUOZHANGSHI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F7_SUOZHANGSHI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x49','0x49',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F7_SUOZHANGSHI_1_OPENCLOSE','OPENCLOSE','LONG');

########################################################################################################################################################################################################################################################################################################################################################################################################
# F8 CURTAIN

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_12_ADJUST','BIAD_KNX_DEVICES&0x714','0x714',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_12_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_12_OPENCLOSE','BIAD_KNX_DEVICES&0x3D','0x3D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_12_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_11_ADJUST','BIAD_KNX_DEVICES&0x713','0x713',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_11_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_11_OPENCLOSE','BIAD_KNX_DEVICES&0x3B','0x3B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_11_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_10_ADJUST','BIAD_KNX_DEVICES&0x712','0x712',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_10_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_10_OPENCLOSE','BIAD_KNX_DEVICES&0x39','0x39',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_10_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_9_ADJUST','BIAD_KNX_DEVICES&0x711','0x711',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_9_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_9_OPENCLOSE','BIAD_KNX_DEVICES&0x37','0x37',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_9_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_8_ADJUST','BIAD_KNX_DEVICES&0x610','0x610',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_8_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_8_OPENCLOSE','BIAD_KNX_DEVICES&0x35','0x35',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_8_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_7_ADJUST','BIAD_KNX_DEVICES&0x60E','0x60E',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_7_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_7_OPENCLOSE','BIAD_KNX_DEVICES&0x31','0x31',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_7_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_6_ADJUST','BIAD_KNX_DEVICES&0x60F','0x60F',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_6_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_6_OPENCLOSE','BIAD_KNX_DEVICES&0x33','0x33',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_6_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_5_ADJUST','BIAD_KNX_DEVICES&0x60D','0x60D',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_5_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_5_OPENCLOSE','BIAD_KNX_DEVICES&0x2F','0x2F',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_5_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_4_ADJUST','BIAD_KNX_DEVICES&0x60C','0x60C',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_4_OPENCLOSE','BIAD_KNX_DEVICES&0x2D','0x2D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_3_ADJUST','BIAD_KNX_DEVICES&0x60B','0x60B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_3_OPENCLOSE','BIAD_KNX_DEVICES&0x2B','0x2B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_2_ADJUST','BIAD_KNX_DEVICES&0x60A','0x60A',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x29','0x29',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_1_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_SUOZHANGSHI_4_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_SUOZHANGSHI_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_SUOZHANGSHI_4_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_SUOZHANGSHI_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XIUXIANSHI_2_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XIUXIANSHI_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XIUXIANSHI_2_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XIUXIANSHI_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XIUXIANSHI_1_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XIUXIANSHI_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_XIUXIANSHI_1_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_XIUXIANSHI_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_4_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_4_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_ZONGJIANSHI_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_ZONGJIANSHI_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_ZONGJIANSHI_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_ZONGJIANSHI_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_SUOZHANGSHI_3_ADJUST','BIAD_KNX_DEVICES&0x609','0x609',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_SUOZHANGSHI_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_SUOZHANGSHI_3_OPENCLOSE','BIAD_KNX_DEVICES&0x27','0x27',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_SUOZHANGSHI_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_1_ADJUST','BIAD_KNX_DEVICES&0x602','0x602',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_1_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_1_OPENCLOSE','BIAD_KNX_DEVICES&0x19','0x19',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_1_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_2_ADJUST','BIAD_KNX_DEVICES&0x623','0x623',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_2_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_2_OPENCLOSE','BIAD_KNX_DEVICES&0x5B','0x5B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_2_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_3_ADJUST','BIAD_KNX_DEVICES&0x622','0x622',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_3_OPENCLOSE','BIAD_KNX_DEVICES&0x59','0x59',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_4_ADJUST','BIAD_KNX_DEVICES&0x601','0x601',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_4_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_4_OPENCLOSE','BIAD_KNX_DEVICES&0x17','0x17',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_4_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_5_ADJUST','BIAD_KNX_DEVICES&0x600','0x600',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_5_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_5_OPENCLOSE','BIAD_KNX_DEVICES&0x15','0x15',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_5_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_6_ADJUST','BIAD_KNX_DEVICES&0x621','0x621',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_6_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_6_OPENCLOSE','BIAD_KNX_DEVICES&0x57','0x57',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_6_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_7_ADJUST','BIAD_KNX_DEVICES&0x620','0x620',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_7_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_7_OPENCLOSE','BIAD_KNX_DEVICES&0x55','0x55',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_7_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_8_ADJUST','BIAD_KNX_DEVICES&0x61E','0x61E',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_8_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_8_OPENCLOSE','BIAD_KNX_DEVICES&0x51','0x51',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_8_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_9_ADJUST','BIAD_KNX_DEVICES&0x61F','0x61F',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_9_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_9_OPENCLOSE','BIAD_KNX_DEVICES&0x53','0x53',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_9_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_10_ADJUST','BIAD_KNX_DEVICES&0x61D','0x61D',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_10_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_10_OPENCLOSE','BIAD_KNX_DEVICES&0x4F','0x4F',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_10_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_11_ADJUST','BIAD_KNX_DEVICES&0x61C','0x61C',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_11_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_11_OPENCLOSE','BIAD_KNX_DEVICES&0x4D','0x4D',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_11_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_12_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_12_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_DONG_12_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_DONG_12_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_3_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_3_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_3_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_3_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_5_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_5_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_5_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_5_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_6_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_6_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_HUIYISHI_6_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_HUIYISHI_6_OPENCLOSE','OPENCLOSE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_CHUTUSHI_ADJUST','BIAD_KNX_DEVICES&0x61B','0x61B',0,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_CHUTUSHI_ADJUST','ADJUST','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('CUR_F8_CHUTUSHI_OPENCLOSE','BIAD_KNX_DEVICES&0x4B','0x4B',1,'http://localhost:8098/AgilorReader/devices/BIAD_KNX_DEVICES/CUR_F8_CHUTUSHI_OPENCLOSE','OPENCLOSE','LONG');


