CREATE DATABASE IF NOT EXISTS ibmsappdb;

USE ibmsappdb;

DROP TABLE IF EXISTS knx_device;
CREATE TABLE IF NOT EXISTS knx_device (

	auto_id INT NOT NULL AUTO_INCREMENT,							# 自增 id

	agilor_aci_name     VARCHAR(64)  NOT NULL,						# agilor 点名，用于 ACI 访问
	agilor_rtdb_name    VARCHAR(64)  NOT NULL,						# agilor 源节点名，用于 RTDB 访问
	agiolor_web_api_url VARCHAR(255) NOT NULL,						# agilor 点对应的 web api 接口的 url 地址，ACI 访问

	knx_group_address        VARCHAR(64)  NOT NULL,					# knx 设备点的组地址
	knx_value_less7bit       TINYINT(1)   NOT NULL,					# knx 设备点值数据长度标志，true 低于 7 位（开关量，枚举量等），false 高于 7 位（模拟量）
	knx_value_type           VARCHAR(64)  NOT NULL,					# knx 设备点值类型，LONG、ENUM
	knx_device_point_type    VARCHAR(64)  NOT NULL,					# knx 设备点类型，单灯（SINGLE），开关模式灯（CONTROL），场景灯（SCENE）， 窗帘升降（UPDOWN），百叶开关（OPENCLOSE）

	PRIMARY KEY ( auto_id ),
	UNIQUE ( agilor_aci_name )
);

########################################################################################################################################################################################################################################################################################################################################################################################################
# F7 LIGHTING

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_SHANG_ZHAO_DENG_S','BIAD_KNX_DEVICES&0xA6','0xA6',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_SHANG_ZHAO_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_SHANG_ZHAO_DENG_M','BIAD_KNX_DEVICES&0xA7','0xA7',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_SHANG_ZHAO_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_SHANG_ZHAO_DENG_N','BIAD_KNX_DEVICES&0xA8','0xA8',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_SHANG_ZHAO_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_SHANG_ZHAO_DENG_S','BIAD_KNX_DEVICES&0xA3','0xA3',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_SHANG_ZHAO_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_SHANG_ZHAO_DENG_M','BIAD_KNX_DEVICES&0xA4','0xA4',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_SHANG_ZHAO_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_SHANG_ZHAO_DENG_N','BIAD_KNX_DEVICES&0xA5','0xA5',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_SHANG_ZHAO_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_TONG_DENG_S','BIAD_KNX_DEVICES&0xCA','0xCA',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_TONG_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_TONG_DENG_M','BIAD_KNX_DEVICES&0xCB','0xCB',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_TONG_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_708_TONG_DENG_N','BIAD_KNX_DEVICES&0xCC','0xCC',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_708_TONG_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_TONG_DENG_S','BIAD_KNX_DEVICES&0xC7','0xC7',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_TONG_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_TONG_DENG_M','BIAD_KNX_DEVICES&0xC8','0xC8',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_TONG_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_TONG_DENG_N','BIAD_KNX_DEVICES&0xC9','0xC9',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_TONG_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_DENG_DAI_S','BIAD_KNX_DEVICES&0x4','0x4',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_DENG_DAI_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_LANG_DENG_S','BIAD_KNX_DEVICES&0xD8','0xD8',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_LANG_DENG_S','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_DENG_DAI_N','BIAD_KNX_DEVICES&0x5','0x5',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_DENG_DAI_N','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_LANG_DENG_N','BIAD_KNX_DEVICES&0xD9','0xD9',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_LANG_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_SHANG_ZHAO_DENG','BIAD_KNX_DEVICES&0xDB','0xDB',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_SHANG_ZHAO_DENG','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_1_E','BIAD_KNX_DEVICES&0xA9','0xA9',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_1_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_1_W','BIAD_KNX_DEVICES&0xAA','0xAA',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_1_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_2_E','BIAD_KNX_DEVICES&0xAB','0xAB',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_2_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_2_W','BIAD_KNX_DEVICES&0xAC','0xAC',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_2_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_SHE_DENG_E','BIAD_KNX_DEVICES&0xAD','0xAD',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_SHE_DENG_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_709_SHE_DENG_W','BIAD_KNX_DEVICES&0xAE','0xAE',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_709_SHE_DENG_W','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_1','BIAD_KNX_DEVICES&0xAF','0xAF',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_1','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_2','BIAD_KNX_DEVICES&0xB0','0xB0',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_2','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_2_WAI','BIAD_KNX_DEVICES&0xB1','0xB1',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_2_WAI','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_QIAN_TAI_DENG','BIAD_KNX_DEVICES&0xCE','0xCE',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_QIAN_TAI_DENG','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_3_WAI','BIAD_KNX_DEVICES&0xB3','0xB3',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_3_WAI','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_3','BIAD_KNX_DEVICES&0xB2','0xB2',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_3','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_YUAN_ZHANG_SHI_4','BIAD_KNX_DEVICES&0xB4','0xB4',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_YUAN_ZHANG_SHI_4','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_SHANG_ZHAO_DENG','BIAD_KNX_DEVICES&0xDA','0xDA',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_SHANG_ZHAO_DENG','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_1_E','BIAD_KNX_DEVICES&0xB5','0xB5',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_1_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_1_W','BIAD_KNX_DEVICES&0xB6','0xB6',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_1_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_2_E','BIAD_KNX_DEVICES&0xB7','0xB7',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_2_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_2_W','BIAD_KNX_DEVICES&0xB8','0xB8',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_2_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_SHE_DENG_E','BIAD_KNX_DEVICES&0xB9','0xB9',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_SHE_DENG_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_712_SHE_DENG_W','BIAD_KNX_DEVICES&0xBA','0xBA',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_712_SHE_DENG_W','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_BA_TAI_DENG','BIAD_KNX_DEVICES&0xCD','0xCD',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_BA_TAI_DENG','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706','LIG_SCENE_706','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706','SCENE','ENUM');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703','LIG_SCENE_703','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703','SCENE','ENUM');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F7_XIU_XIAN_SHI','BIAD_KNX_DEVICES&0xA','0xA',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F7_XIU_XIAN_SHI','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_E','BIAD_KNX_DEVICES&0xBD','0xBD',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_701_W','BIAD_KNX_DEVICES&0xBE','0xBE',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_701_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_706_E','BIAD_KNX_DEVICES&0xBC','0xBC',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_706_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_706_W','BIAD_KNX_DEVICES&0xD7','0xD7',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_706_W','SINGLE','LONG');


INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_21_S','BIAD_KNX_DEVICES&0x328','0x328',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_21_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_21_N','BIAD_KNX_DEVICES&0x329','0x329',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_21_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_20_S','BIAD_KNX_DEVICES&0x326','0x326',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_20_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_20_N','BIAD_KNX_DEVICES&0x327','0x327',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_20_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_19_S','BIAD_KNX_DEVICES&0x324','0x324',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_19_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_19_N','BIAD_KNX_DEVICES&0x325','0x325',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_19_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_18_S','BIAD_KNX_DEVICES&0x322','0x322',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_18_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_18_N','BIAD_KNX_DEVICES&0x323','0x323',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_18_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_17_S','BIAD_KNX_DEVICES&0x320','0x320',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_17_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_17_N','BIAD_KNX_DEVICES&0x321','0x321',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_17_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_16_S','BIAD_KNX_DEVICES&0x31E','0x31E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_16_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_16_N','BIAD_KNX_DEVICES&0x31F','0x31F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_16_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_15_S','BIAD_KNX_DEVICES&0x31C','0x31C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_15_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_15_N','BIAD_KNX_DEVICES&0x31D','0x31D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_15_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_14_S','BIAD_KNX_DEVICES&0x31A','0x31A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_14_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_14_N','BIAD_KNX_DEVICES&0x31B','0x31B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_14_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_13_S','BIAD_KNX_DEVICES&0x318','0x318',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_13_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_13_N','BIAD_KNX_DEVICES&0x319','0x319',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_13_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_12_S','BIAD_KNX_DEVICES&0x316','0x316',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_12_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_12_N','BIAD_KNX_DEVICES&0x317','0x317',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_12_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_11_S','BIAD_KNX_DEVICES&0x314','0x314',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_11_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_11_N','BIAD_KNX_DEVICES&0x315','0x315',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_11_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_10_S','BIAD_KNX_DEVICES&0x312','0x312',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_10_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_10_N','BIAD_KNX_DEVICES&0x313','0x313',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_10_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_09_S','BIAD_KNX_DEVICES&0x310','0x310',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_09_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_09_N','BIAD_KNX_DEVICES&0x311','0x311',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_09_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_08_S','BIAD_KNX_DEVICES&0x30E','0x30E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_08_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_08_N','BIAD_KNX_DEVICES&0x30F','0x30F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_08_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_07_S','BIAD_KNX_DEVICES&0x30C','0x30C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_07_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_07_N','BIAD_KNX_DEVICES&0x30D','0x30D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_07_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_06_S','BIAD_KNX_DEVICES&0x30A','0x30A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_06_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_06_N','BIAD_KNX_DEVICES&0x30B','0x30B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_06_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_05_S','BIAD_KNX_DEVICES&0x308','0x308',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_05_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_05_N','BIAD_KNX_DEVICES&0x309','0x309',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_05_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_04_S','BIAD_KNX_DEVICES&0x306','0x306',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_04_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_04_N','BIAD_KNX_DEVICES&0x307','0x307',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_04_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_03_S','BIAD_KNX_DEVICES&0x304','0x304',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_03_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_03_N','BIAD_KNX_DEVICES&0x305','0x305',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_03_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_02_S','BIAD_KNX_DEVICES&0x302','0x302',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_02_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_02_N','BIAD_KNX_DEVICES&0x303','0x303',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_02_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_01_S','BIAD_KNX_DEVICES&0x300','0x300',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_01_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_708_01_N','BIAD_KNX_DEVICES&0x301','0x301',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_708_01_N','SINGLE','LONG');


INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_21_S','BIAD_KNX_DEVICES&0x352','0x352',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_21_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_21_N','BIAD_KNX_DEVICES&0x353','0x353',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_21_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_20_S','BIAD_KNX_DEVICES&0x350','0x350',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_20_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_20_N','BIAD_KNX_DEVICES&0x351','0x351',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_20_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_19_S','BIAD_KNX_DEVICES&0x34E','0x34E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_19_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_19_N','BIAD_KNX_DEVICES&0x34F','0x34F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_19_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_18_S','BIAD_KNX_DEVICES&0x34C','0x34C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_18_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_18_N','BIAD_KNX_DEVICES&0x34D','0x34D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_18_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_17_S','BIAD_KNX_DEVICES&0x34A','0x34A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_17_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_17_N','BIAD_KNX_DEVICES&0x34B','0x34B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_17_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_16_S','BIAD_KNX_DEVICES&0x348','0x348',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_16_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_16_N','BIAD_KNX_DEVICES&0x349','0x349',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_16_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_15_S','BIAD_KNX_DEVICES&0x346','0x346',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_15_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_15_N','BIAD_KNX_DEVICES&0x347','0x347',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_15_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_14_S','BIAD_KNX_DEVICES&0x344','0x344',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_14_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_14_N','BIAD_KNX_DEVICES&0x345','0x345',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_14_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_13_S','BIAD_KNX_DEVICES&0x342','0x342',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_13_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_13_N','BIAD_KNX_DEVICES&0x343','0x343',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_13_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_12_S','BIAD_KNX_DEVICES&0x340','0x340',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_12_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_12_N','BIAD_KNX_DEVICES&0x341','0x341',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_12_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_11_S','BIAD_KNX_DEVICES&0x33E','0x33E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_11_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_11_N','BIAD_KNX_DEVICES&0x33F','0x33F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_11_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_10_S','BIAD_KNX_DEVICES&0x33C','0x33C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_10_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_10_N','BIAD_KNX_DEVICES&0x33D','0x33D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_10_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_09_S','BIAD_KNX_DEVICES&0x33A','0x33A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_09_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_09_N','BIAD_KNX_DEVICES&0x33B','0x33B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_09_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_08_S','BIAD_KNX_DEVICES&0x338','0x338',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_08_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_08_N','BIAD_KNX_DEVICES&0x339','0x339',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_08_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_07_S','BIAD_KNX_DEVICES&0x336','0x336',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_07_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_07_N','BIAD_KNX_DEVICES&0x337','0x337',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_07_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_06_S','BIAD_KNX_DEVICES&0x334','0x334',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_06_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_06_N','BIAD_KNX_DEVICES&0x335','0x335',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_06_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_05_S','BIAD_KNX_DEVICES&0x332','0x332',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_05_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_05_N','BIAD_KNX_DEVICES&0x333','0x333',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_05_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_04_S','BIAD_KNX_DEVICES&0x330','0x330',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_04_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_04_N','BIAD_KNX_DEVICES&0x331','0x331',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_04_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_03_S','BIAD_KNX_DEVICES&0x32E','0x32E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_03_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_03_N','BIAD_KNX_DEVICES&0x32F','0x32F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_03_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_02_S','BIAD_KNX_DEVICES&0x32C','0x32C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_02_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_02_N','BIAD_KNX_DEVICES&0x32D','0x32D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_02_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_01_S','BIAD_KNX_DEVICES&0x32A','0x32A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_01_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_701_01_N','BIAD_KNX_DEVICES&0x32B','0x32B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_701_01_N','SINGLE','LONG');



########################################################################################################################################################################################################################################################################################################################################################################################################
# F8 LIGHTING

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_SHANG_ZHAO_DENG_S','BIAD_KNX_DEVICES&0x1AC','0x1AC',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_SHANG_ZHAO_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_SHANG_ZHAO_DENG_M','BIAD_KNX_DEVICES&0x1AD','0x1AD',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_SHANG_ZHAO_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_SHANG_ZHAO_DENG_N','BIAD_KNX_DEVICES&0x1AE','0x1AE',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_SHANG_ZHAO_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_SHANG_ZHAO_DENG_S','BIAD_KNX_DEVICES&0x1A9','0x1A9',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_SHANG_ZHAO_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_SHANG_ZHAO_DENG_M','BIAD_KNX_DEVICES&0x1AA','0x1AA',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_SHANG_ZHAO_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_SHANG_ZHAO_DENG_N','BIAD_KNX_DEVICES&0x1AB','0x1AB',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_SHANG_ZHAO_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_TONG_DENG_S','BIAD_KNX_DEVICES&0x1C0','0x1C0',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_TONG_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_TONG_DENG_M','BIAD_KNX_DEVICES&0x1BF','0x1BF',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_TONG_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_808_TONG_DENG_N','BIAD_KNX_DEVICES&0x1C1','0x1C1',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_808_TONG_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_TONG_DENG_S','BIAD_KNX_DEVICES&0x1BD','0x1BD',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_TONG_DENG_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_TONG_DENG_M','BIAD_KNX_DEVICES&0x1BC','0x1BC',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_TONG_DENG_M','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_TONG_DENG_N','BIAD_KNX_DEVICES&0x1BE','0x1BE',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_TONG_DENG_N','CONTROL','LONG');


INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_DENG_DAI_S','BIAD_KNX_DEVICES&0x103','0x103',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_DENG_DAI_S','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_LANG_DENG_S','BIAD_KNX_DEVICES&0x1C8','0x1C8',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_LANG_DENG_S','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_DENG_DAI_N','BIAD_KNX_DEVICES&0x104','0x104',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_DENG_DAI_N','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_LANG_DENG_N','BIAD_KNX_DEVICES&0x1C9','0x1C9',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_LANG_DENG_N','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_810_SHANG_ZHAO_DENG','BIAD_KNX_DEVICES&0x1CA','0x1CA',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_810_SHANG_ZHAO_DENG','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_810_E','BIAD_KNX_DEVICES&0x1CB','0x1CB',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_810_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_810_W','BIAD_KNX_DEVICES&0x1CC','0x1CC',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_810_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_810_SHE_DENG_E','BIAD_KNX_DEVICES&0x1B1','0x1B1',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_810_SHE_DENG_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_810_SHE_DENG_W','BIAD_KNX_DEVICES&0x1B2','0x1B2',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_810_SHE_DENG_W','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_BA_TAI_DENG_E','BIAD_KNX_DEVICES&0x1CE','0x1CE',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_BA_TAI_DENG_E','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_BA_TAI_DENG_W','BIAD_KNX_DEVICES&0x1CD','0x1CD',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_BA_TAI_DENG_W','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_F8_XIU_XIAN_SHI','BIAD_KNX_DEVICES&0x109','0x109',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_F8_XIU_XIAN_SHI','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_E','BIAD_KNX_DEVICES&0x1AF','0x1AF',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_801_W','BIAD_KNX_DEVICES&0x1B0','0x1B0',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_801_W','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_806_E','BIAD_KNX_DEVICES&0x1B4','0x1B4',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_806_E','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_OTHER_806_W','BIAD_KNX_DEVICES&0x1B5','0x1B5',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_OTHER_806_W','SINGLE','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3','LIG_SCENE_F8_HUIYISHI_3','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3','SCENE','ENUM');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4','LIG_SCENE_F8_HUIYISHI_4','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4','SCENE','ENUM');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5','LIG_SCENE_F8_HUIYISHI_5','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5','SCENE','ENUM');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6','LIG_SCENE_F8_HUIYISHI_6','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6','SCENE','ENUM');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI','LIG_SCENE_F8_DAHUIYI','',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI','SCENE','ENUM');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_21_S','BIAD_KNX_DEVICES&0x228','0x228',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_21_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_21_N','BIAD_KNX_DEVICES&0x229','0x229',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_21_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_20_S','BIAD_KNX_DEVICES&0x226','0x226',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_20_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_20_N','BIAD_KNX_DEVICES&0x227','0x227',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_20_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_19_S','BIAD_KNX_DEVICES&0x224','0x224',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_19_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_19_N','BIAD_KNX_DEVICES&0x225','0x225',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_19_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_18_S','BIAD_KNX_DEVICES&0x222','0x222',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_18_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_18_N','BIAD_KNX_DEVICES&0x223','0x223',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_18_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_17_S','BIAD_KNX_DEVICES&0x220','0x220',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_17_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_17_N','BIAD_KNX_DEVICES&0x221','0x221',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_17_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_16_S','BIAD_KNX_DEVICES&0x21E','0x21E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_16_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_16_N','BIAD_KNX_DEVICES&0x21F','0x21F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_16_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_15_S','BIAD_KNX_DEVICES&0x21C','0x21C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_15_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_15_N','BIAD_KNX_DEVICES&0x21D','0x21D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_15_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_14_S','BIAD_KNX_DEVICES&0x21A','0x21A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_14_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_14_N','BIAD_KNX_DEVICES&0x21B','0x21B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_14_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_13_S','BIAD_KNX_DEVICES&0x218','0x218',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_13_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_13_N','BIAD_KNX_DEVICES&0x219','0x219',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_13_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_12_S','BIAD_KNX_DEVICES&0x216','0x216',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_12_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_12_N','BIAD_KNX_DEVICES&0x217','0x217',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_12_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_11_S','BIAD_KNX_DEVICES&0x214','0x214',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_11_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_11_N','BIAD_KNX_DEVICES&0x215','0x215',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_11_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_10_S','BIAD_KNX_DEVICES&0x212','0x212',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_10_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_10_N','BIAD_KNX_DEVICES&0x213','0x213',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_10_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_09_S','BIAD_KNX_DEVICES&0x210','0x210',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_09_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_09_N','BIAD_KNX_DEVICES&0x211','0x211',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_09_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_08_S','BIAD_KNX_DEVICES&0x20E','0x20E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_08_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_08_N','BIAD_KNX_DEVICES&0x20F','0x20F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_08_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_07_S','BIAD_KNX_DEVICES&0x20C','0x20C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_07_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_07_N','BIAD_KNX_DEVICES&0x20D','0x20D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_07_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_06_S','BIAD_KNX_DEVICES&0x20A','0x20A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_06_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_06_N','BIAD_KNX_DEVICES&0x20B','0x20B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_06_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_05_S','BIAD_KNX_DEVICES&0x208','0x208',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_05_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_05_N','BIAD_KNX_DEVICES&0x209','0x209',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_05_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_04_S','BIAD_KNX_DEVICES&0x206','0x206',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_04_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_04_N','BIAD_KNX_DEVICES&0x207','0x207',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_04_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_03_S','BIAD_KNX_DEVICES&0x204','0x204',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_03_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_03_N','BIAD_KNX_DEVICES&0x205','0x205',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_03_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_02_S','BIAD_KNX_DEVICES&0x202','0x202',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_02_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_02_N','BIAD_KNX_DEVICES&0x203','0x203',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_02_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_01_S','BIAD_KNX_DEVICES&0x200','0x200',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_01_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_808_01_N','BIAD_KNX_DEVICES&0x201','0x201',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_808_01_N','SINGLE','LONG');


INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_21_S','BIAD_KNX_DEVICES&0x252','0x252',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_21_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_21_N','BIAD_KNX_DEVICES&0x253','0x253',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_21_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_20_S','BIAD_KNX_DEVICES&0x250','0x250',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_20_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_20_N','BIAD_KNX_DEVICES&0x251','0x251',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_20_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_19_S','BIAD_KNX_DEVICES&0x24E','0x24E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_19_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_19_N','BIAD_KNX_DEVICES&0x24F','0x24F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_19_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_18_S','BIAD_KNX_DEVICES&0x24C','0x24C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_18_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_18_N','BIAD_KNX_DEVICES&0x24D','0x24D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_18_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_17_S','BIAD_KNX_DEVICES&0x24A','0x24A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_17_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_17_N','BIAD_KNX_DEVICES&0x24B','0x24B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_17_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_16_S','BIAD_KNX_DEVICES&0x248','0x248',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_16_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_16_N','BIAD_KNX_DEVICES&0x249','0x249',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_16_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_15_S','BIAD_KNX_DEVICES&0x246','0x246',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_15_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_15_N','BIAD_KNX_DEVICES&0x247','0x247',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_15_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_14_S','BIAD_KNX_DEVICES&0x244','0x244',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_14_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_14_N','BIAD_KNX_DEVICES&0x245','0x245',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_14_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_13_S','BIAD_KNX_DEVICES&0x242','0x242',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_13_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_13_N','BIAD_KNX_DEVICES&0x243','0x243',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_13_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_12_S','BIAD_KNX_DEVICES&0x240','0x240',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_12_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_12_N','BIAD_KNX_DEVICES&0x241','0x241',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_12_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_11_S','BIAD_KNX_DEVICES&0x23E','0x23E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_11_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_11_N','BIAD_KNX_DEVICES&0x23F','0x23F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_11_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_10_S','BIAD_KNX_DEVICES&0x23C','0x23C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_10_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_10_N','BIAD_KNX_DEVICES&0x23D','0x23D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_10_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_09_S','BIAD_KNX_DEVICES&0x23A','0x23A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_09_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_09_N','BIAD_KNX_DEVICES&0x23B','0x23B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_09_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_08_S','BIAD_KNX_DEVICES&0x238','0x238',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_08_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_08_N','BIAD_KNX_DEVICES&0x239','0x239',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_08_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_07_S','BIAD_KNX_DEVICES&0x236','0x236',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_07_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_07_N','BIAD_KNX_DEVICES&0x237','0x237',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_07_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_06_S','BIAD_KNX_DEVICES&0x234','0x234',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_06_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_06_N','BIAD_KNX_DEVICES&0x235','0x235',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_06_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_05_S','BIAD_KNX_DEVICES&0x232','0x232',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_05_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_05_N','BIAD_KNX_DEVICES&0x233','0x233',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_05_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_04_S','BIAD_KNX_DEVICES&0x230','0x230',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_04_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_04_N','BIAD_KNX_DEVICES&0x231','0x231',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_04_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_03_S','BIAD_KNX_DEVICES&0x22E','0x22E',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_03_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_03_N','BIAD_KNX_DEVICES&0x22F','0x22F',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_03_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_02_S','BIAD_KNX_DEVICES&0x22C','0x22C',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_02_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_02_N','BIAD_KNX_DEVICES&0x22D','0x22D',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_02_N','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_01_S','BIAD_KNX_DEVICES&0x22A','0x22A',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_01_S','SINGLE','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_801_01_N','BIAD_KNX_DEVICES&0x22B','0x22B',0,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_801_01_N','SINGLE','LONG');


########################################################################################################################################################################################################################################################################################################################################################################################################
# F7 LIGHTING SCENE

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706__ALL_ON','BIAD_KNX_DEVICES&0x535','0x535',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706__ALL_OFF','BIAD_KNX_DEVICES&0x536','0x536',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706__NORMAL','BIAD_KNX_DEVICES&0x537','0x537',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x538','0x538',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_706__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x539','0x539',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_706__PLAYWITHOUTPEOPLE','CONTROL','LONG');


INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703__ALL_ON','BIAD_KNX_DEVICES&0x501','0x501',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703__ALL_OFF','BIAD_KNX_DEVICES&0x502','0x502',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703__NORMAL','BIAD_KNX_DEVICES&0x503','0x503',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x504','0x504',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_703__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x505','0x505',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_703__PLAYWITHPEOPLE','CONTROL','LONG');

########################################################################################################################################################################################################################################################################################################################################################################################################
# F8 LIGHTING SCENE

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3__ALL_ON','BIAD_KNX_DEVICES&0x57F','0x57F',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3__ALL_OFF','BIAD_KNX_DEVICES&0x580','0x580',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3__NORMAL','BIAD_KNX_DEVICES&0x581','0x581',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x582','0x582',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_3__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x583','0x583',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_3__PLAYWITHPEOPLE','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI__ALL_ON','BIAD_KNX_DEVICES&0x512','0x512',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI__ALL_OFF','BIAD_KNX_DEVICES&0x513','0x513',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI__NORMAL','BIAD_KNX_DEVICES&0x514','0x514',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x515','0x515',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_DAHUIYI__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x516','0x516',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_DAHUIYI__PLAYWITHPEOPLE','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4__ALL_ON','BIAD_KNX_DEVICES&0x546','0x546',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4__ALL_OFF','BIAD_KNX_DEVICES&0x547','0x547',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4__NORMAL','BIAD_KNX_DEVICES&0x548','0x548',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x549','0x549',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_4__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x54A','0x54A',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_4__PLAYWITHPEOPLE','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5__ALL_ON','BIAD_KNX_DEVICES&0x5A1','0x5A1',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5__ALL_OFF','BIAD_KNX_DEVICES&0x5A2','0x5A2',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5__NORMAL','BIAD_KNX_DEVICES&0x5A3','0x5A3',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x5A4','0x5A4',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_5__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x5A5','0x5A5',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_5__PLAYWITHPEOPLE','CONTROL','LONG');

INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6__ALL_ON','BIAD_KNX_DEVICES&0x590','0x590',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6__ALL_ON','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6__ALL_OFF','BIAD_KNX_DEVICES&0x591','0x591',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6__ALL_OFF','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6__NORMAL','BIAD_KNX_DEVICES&0x592','0x592',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6__NORMAL','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6__PLAYWITHOUTPEOPLE','BIAD_KNX_DEVICES&0x593','0x593',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6__PLAYWITHOUTPEOPLE','CONTROL','LONG');
INSERT INTO knx_device ( agilor_aci_name, agilor_rtdb_name, knx_group_address, knx_value_less7bit, agiolor_web_api_url, knx_device_point_type, knx_value_type ) VALUES ('LIG_SCENE_F8_HUIYISHI_6__PLAYWITHPEOPLE','BIAD_KNX_DEVICES&0x594','0x594',1,'http://localhost:8098/Agilor/devices/BIAD_KNX_DEVICES/LIG_SCENE_F8_HUIYISHI_6__PLAYWITHPEOPLE','CONTROL','LONG');
