<?php

define("LOGIN_INIT", 0);
define("LOGIN_SUCCESS", 1);
define("LOGIN_FAILED_USER_NOT_EXIST", -1);
define("LOGIN_FAILED_PASSWORD_ERROR", -2);
define("LOGIN_FAILED_SYSTEM", -3);
define("LOGIN_FAILED_ILLEGALLY", -4);
define("LOGIN_FAILED_SESSION_OUTTIME", -5);
define("LOGIN_FAILED_COOKIE_OUTTIME", -6);


define("LOGIN_COOKIE_OUTTIME_SECOND", 60);

?>